### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by dingkou** [erans/pysnowflake#5]
[解释.txt](https://github.com/erans/pysnowflake/files/2788045/default.txt)

**Comment by luohaifenglight** [comment]
> [解释.txt](https://github.com/erans/pysnowflake/files/2788045/default.txt)

Python3就会这样，这里的版本应该是Python2

**Comment by luohaifenglight** [comment]
> [解释.txt](https://github.com/erans/pysnowflake/files/2788045/default.txt)

https://github.com/luohaifenglight/snowflakeservice.git   我这个支持python2,3 并且无依赖，可以自己方便改造。也可以独立使用做成分布式服务。

**Comment by erans** [comment]
Not sure why you have opened an issue. I see that you have taken the idworker.py and put it in a new repo and slightly changed it so it won't have any dependencies on Thrift.
